### ISSUE TITLE
SHA1 mismatch for adobe-air-sdk

### ISSUE THREAD

**Issue by ydesgagn** [Homebrew/homebrew#36761]
Hi,

I always get an SHA1 mismatch when trying to install adobe-air-sdk

brew install adobe-air-sdk
==> Downloading http://airdownload.adobe.com/air/mac/download/16.0/AIRSDK_Compil
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: ee487b3c0456ba825dd6af48682ba81802ef0300
Actual: 5ed2481de822e7f557db33c1bbff9b30e7df4735
Archive: /Library/Caches/Homebrew/adobe-air-sdk-16.0.0.272.tbz2
To retry an incomplete download, remove the file above.

Thanks,

Yves

**Comment by DomT4** [comment]
Fixed in #36772.

**Comment by ydesgagn** [comment]
I still see the problem even after an update.

Thanks,

Yves

**Comment by DomT4** [comment]
Hasn't been merged yet, which is why you're still seeing the issue :). It will probably be merged at some point in the next 12 hours.
