### ISSUE TITLE
Sandbox breaks Git compile

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#38978]
CC @xu-cheng

This is how I build ` git `: ` Built from source with: --with-brewed-curl, --with-brewed-openssl, --with-brewed-svn, --with-gettext, --with-pcre, --with-persistent-https `.

This is the build failure:

```
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.3.6.tar.xz
Already downloaded: /usr/local/var/homebrew/cache/git--html-2.3.6.tar.xz
==> Verifying git--html-2.3.6.tar.xz checksum
==> Sandbox profile:
(version 1)
(debug deny) ; log all denied operations to /var/log/system.log
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (regex #"^/private/var/folders/[^/]+/[^/]+/[C,T]/"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/usr/local/var/homebrew/cache"))
(allow file-write* (subpath "/usr/local/var/homebrew/logs/git"))
(allow file-write* (subpath "/usr/local/Cellar/git"))
(allow file-write* (subpath "/usr/local/etc"))
(allow file-write* (subpath "/usr/local/var"))
(allow file-write*
    (literal "/dev/dtracehelper")
    (literal "/dev/null")
    (regex #"^/dev/fd/\d+$")
    (regex #"^/dev/tty\d*$")
    )
(deny file-write*) ; deny non-whitelist file write operations
(allow default) ; allow everything else
syslog -F '$((Time)(local)) $(Sender)[$(PID)]: $Message' -k Time ge 1429803721 -k Sender kernel -o -k Time ge 1429803721 -k Sender sandboxd | grep deny > /usr/local/var/homebrew/logs/git/sandbox.build.log
Error: Invalid argument - /tmp/git20150423-97011-1s20dgc/git-2.3.6/git-count-objects
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1433:in `unlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1433:in `block in remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1438:in `platform_support'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1432:in `remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1421:in `remove'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:770:in `block in remove_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1471:in `block (2 levels) in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1471:in `block (2 levels) in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1475:in `postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1470:in `block in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1470:in `block in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:768:in `remove_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:626:in `block in rm_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:622:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:622:in `rm_r'
/usr/local/Library/Homebrew/extend/fileutils.rb:22:in `block in mktemp'
/usr/local/Library/Homebrew/utils.rb:265:in `ignore_interrupts'
/usr/local/Library/Homebrew/extend/fileutils.rb:22:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:876:in `stage'
/usr/local/Library/Homebrew/formula.rb:507:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

` unset HOMEBREW_SANDBOX ` followed by re-doing the Git build works fine.

**Comment by xu-cheng** [comment]
Can you paste the gist log? It contains sandbox log.

**Comment by DomT4** [comment]
Sure, will get Brew to kick one out. One sec.

**Comment by DomT4** [comment]
https://gist.github.com/anonymous/572c2752bf2135670e1c

**Comment by DomT4** [comment]
If it's relevant, I'm getting a different error every single time I run the build under sandbox with the options in the first post. Just tried the build again prior to that gist-logs, and the error this time was:

```
syslog -F '$((Time)(local)) $(Sender)[$(PID)]: $Message' -k Time ge 1429804575 -k Sender kernel -o -k Time ge 1429804575 -k Sender sandboxd | grep deny > /usr/local/var/homebrew/logs/git/sandbox.build.log
Error: Invalid argument - /tmp/git20150423-11953-1bkjftp/git-2.3.6/git-fsck
```

**Comment by xu-cheng** [comment]
The way I get sandbox log is to get all deny log after build started. So the time will be changed. In the same time, some unrelated log (deny operations caused by other process in that period time) will be recorded. 

Quick scan your log, sandbox didn't block any operation. I'm away my Mac now and will try to reproduce your error tomorrow.

**Comment by DomT4** [comment]
No worries, will unset the sandbox for now to install Git. Shout if you need anything else to chase the problem up.

**Comment by jacknagel** [comment]
I see this also. It's happening while the tmpdir is being cleaned up.

The `File.unlink` call is raising `Errno::EINVAL` on line 1433 of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb.

**Comment by xu-cheng** [comment]
After some experiments, these are what I know so far.
* It relates to sandbox, but there is no log to show any block or deny operations.
* It has something to do the system `unlink` call. If I go to the interactive shell(with sandbox enable) and run `rm -rf <temp dir path>`, it will show similar `invalid argument` error. If I try to run the `rm -rf` command again, everything will be fine. If I just run `rm <one of temp files>`, everything work fine as well.
* Except the large number of hard links, I see no anomaly in the related files. There is no ACL or any other strange file attributes or permissions.

**Comment by DomT4** [comment]
Potentially found another breakage.

```ruby
  test do
    assert_match /#{version}/, shell_output("#{sbin}/dovecot --version")
  end
```

Under sandboxing:

```
Dominyks-MacBook-Pro ~> brew test --verbose dovecot                                              (dovecot) [/usr/local]
Testing dovecot
Error: dovecot: failed
undefined local variable or method `formula' for Homebrew:Module
/usr/local/Library/Homebrew/cmd/test.rb:41:in `block (2 levels) in test'
/usr/local/Library/Homebrew/utils/fork.rb:16:in `block (3 levels) in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:10:in `fork'
/usr/local/Library/Homebrew/utils/fork.rb:10:in `block (2 levels) in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/cmd/test.rb:38:in `block in test'
/usr/local/Library/Homebrew/cmd/test.rb:11:in `each'
/usr/local/Library/Homebrew/cmd/test.rb:11:in `test'
/usr/local/Library/brew.rb:140:in `<main>'
```

Works with sandbox unset.

**Comment by jacknagel** [comment]
@DomT4 fixed in 78fcc8b6b1949abbcf0ce4812e02297abc12691b

**Comment by DomT4** [comment]
Thanks Jack!

**Comment by xu-cheng** [comment]
Fixed in f20dafab85bd33c073824de7416340bdbedc4e0d. But leaving this ticket open as jacknagel  suggested.

**Comment by jacknagel** [comment]
So using rm_rf doesn't actually fix anything, it just hides the errors. The end result is that the temporary directory is not completely removed after the build.

We need to figure out what is causing this. Are we all testing this on 10.10? We should try older versions, perhaps it's a new bug?

**Comment by DomT4** [comment]
Tested on 10.10.4 here.

**Comment by jacknagel** [comment]
Can't reproduce this on 10.9.

**Comment by xu-cheng** [comment]
> So using rm_rf doesn't actually fix anything, it just hides the errors. The end result is that the temporary directory is not completely removed after the build.

Yes, I just find it as well.

> We need to figure out what is causing this

This could be hard. On the one hand, I still fail to find what makes git temp files different. On the other hand, I can reproduce this bug outside of homebrew. It could very be a bug caused by Apple.

> Are we all testing this on 10.10? We should try older versions, perhaps it's a new bug?

I only have the latest OS to test from. I wonder how to install old OS VM on my Parallel Desktop 9.

A dirty hack solution would be like this. And again, we still fail to find the root cause.

```diff
diff --git a/Library/Homebrew/extend/fileutils.rb b/Library/Homebrew/extend/fileutils.rb
index 4778d90..d7d941f 100644
--- a/Library/Homebrew/extend/fileutils.rb
+++ b/Library/Homebrew/extend/fileutils.rb
@@ -19,7 +19,10 @@ module FileUtils
         cd(prev)
       end
     ensure
-      ignore_interrupts { rm_rf(tmp) }
+      ignore_interrupts do
+        rm_rf(tmp)
+        rm_r(tmp) if File.exist?(tmp)
+      end
     end
   end
   module_function :mktemp
```

**Comment by jacknagel** [comment]
Since I can't reproduce it on 10.9, if we can come up with a script for reproducing it outside of Homebrew, we can report it to Apple.

**Comment by xu-cheng** [comment]
OK, I will add this into my todo list. (I'm busy next week because the final exam).

**Comment by xu-cheng** [comment]
I made a small reproducing demo here: https://gist.github.com/xu-cheng/00cf4d4f4b385bc9aa74 Can your guys help to test it on different version OS X?

**Comment by DomT4** [comment]
Reproduces on 10.10.4:

```
==> Try to delete files, but it will show errors:
rm: git-2.4.0/git-log: Invalid argument
rm: git-2.4.0: Directory not empty
==> Try again, this time it works fine
```

**Comment by mikemcquaid** [comment]
@DomT4 @xu-cheng I think this was fixed, right?

**Comment by DomT4** [comment]
I'm no longer on Yosemite, but I can't reproduce on El Cap at this point and it never reached further back than Yosemite. If it's not happening on 10.10 any more, we'd be golden.

**Comment by mikemcquaid** [comment]
I'm 99% sure we've shipped new Git bottles since this was opened and with sandbox enabled so closing this.
