### ISSUE TITLE
git-annex broken after latest update

### ISSUE THREAD

**Issue by psibre** [Homebrew/homebrew#40263]
The `git-annex-shell` symlink is no longer created in version 5.20150522, as
b05ac8b6d62b141c8d2f1def046b1fb6ab28c0c7 removed the corresponding stanza. This essentially breaks git-annex, as it is no longer possible to sync files through SSH; the client gets
```
bash: git-annex-shell: command not found

  Remote REMOTE does not have git-annex installed; setting annex-ignore

  This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git config remote.REMOTE.annex-ignore false
```
If the remote has the previous homebrew version of git-annex (5.20150205), everything is fine.

**Comment by psibre** [comment]
So it's a regression of #30160

**Comment by mikemcquaid** [comment]
@psibre Sorry about that. Could you try and open a pull request to re-add it and, ideally, add it to the `test do` block so it doesn't get accidentally removed in future? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by psibre** [comment]
@mikemcquaid I'm not sure why, but restoring the `bin.install_symlink` command doesn't seem to do anything. Perhaps the install config was changed so that the `git-annex-shell` symlink is not created in `#{prefix}/bin`, so that there is no valid target for the `#{HOMEBREW_PREFIX}/bin/git-annex-shell` symlink?
Incidentally, git-annex was updated again a few days ago, the new version is 5.20150528, but trying to build it causes other errors:
```
$ brew install git-annex
==> Downloading https://homebrew.bintray.com/bottles/git-annex-5.20150528.mountain_lion.bottle.tar.gz

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "git-annex"
Download failed: https://homebrew.bintray.com/bottles/git-annex-5.20150528.mountain_lion.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://hackage.haskell.org/package/git-annex-5.20150528/git-annex-5.20150528.tar.gz
Already downloaded: /Library/Caches/Homebrew/git-annex-5.20150528.tar.gz
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=8 alex
==> cabal install --jobs=8 happy
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x108ccb970>::GitAnnex (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181
Error: marshal data too short
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Library/Homebrew/utils/fork.rb:39:in `safe_fork'
/usr/local/Library/Homebrew/utils.rb:277:in `ignore_interrupts'
/usr/local/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/tmpdir.rb:129:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:482:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `send'
/usr/local/Library/brew.rb:140
```

**Comment by mikemcquaid** [comment]
@psibre That error has been fixed and you shouldn't see it again. I'm not sure about the package itself, I'm afraid.

**Comment by psibre** [comment]
@mikemcquaid Thanks for the update!
Unfortunately, I still cannot get the `bin.install_symlink` to do anything at all. I also notice that none of the other formulas that use `cabal_sandbox` use `bin.install_symlink`. Is it possible that the latter does not work when using the former?

**Comment by mikemcquaid** [comment]
@psibre There shouldn't be anything that interferes there? You could try using `ln_sf` and see if that works? Regardless, if you open a PR we should be able to help you debug.

**Comment by DomT4** [comment]
Status update here?

**Comment by psibre** [comment]
I see three separate issues at this point:
* the symlink is not being created
* git-annex has released at least two newer versions upstream
* building it from source results in dependency hell on the cabal/haskell end

Meanwhile a simple workaround is to manually create a symlink in `/usr/local/bin` named `git-annex-shell`, pointing to the `git-annex` binary in your Cellar, along the lines of:
```
$ ll `which git-annex-shell`
lrwxr-xr-x  1 psibre  admin  44 Jun 11 14:51 /usr/local/bin/git-annex-shell -> ../Cellar/git-annex/5.20150522/bin/git-annex
```
