### ISSUE TITLE
Help with installation of mongoose 5.6

### ISSUE THREAD

**Issue by pig-raffles** [Homebrew/homebrew#40369]
Hi, 

I am relatively inexperience computer user, so please keep any responses as simple as possible.

I am trying to install the web-server mongoose on a IMac running Yosemite. The main purpose of doing this is to use a bioinformatic analysis program called trinotate

I have sucessfully (apparently) installed mongoose-5.6  using homebrew

however when I use the command 'mongoose', I get: 'mongoose: command not found'

When looking at the homebrew installation via: find /usr/local/Cellar/ -name 'mongoose'

I only get:  '/usr/local/Cellar//mongoose'

Upon changing to this directory I get the following files:

INSTALL_RECEIPT.json    README.md        lib
LICENSE            include            share

There appears to be no binary files present, following the installation

Is this a general problem with this version of mongoose, a problem with the installation formula or a problem with my own system? I have run brew doctor and it has flagged up no problems

Does anyone have any (simple) advice to rectify this situation? 

Many thanks

Alan

**Comment by DomT4** [comment]
Fixed by https://github.com/Homebrew/homebrew/commit/a5ba3cd69fbaafd2d2367728e3f36a8873784c9f. `brew reinstall mongoose` will sort it for you. Thanks for the report!

**Comment by pig-raffles** [comment]
Hi,

I am still getting the same problems with the homebrew installation of
Mongoose, has this problem been addressed yet?

Best wishes

Alan

**Comment by DomT4** [comment]
Yes. Make sure your Homebrew is up-to-date (`brew update`) and then do `brew reinstall mongoose`.

**Comment by pig-raffles** [comment]
fantastic thanks, forgot the brew update bit
