### ISSUE TITLE
Error: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by marcusguttenplan** [Homebrew/homebrew#41640]
Hello,

I'm sorry to open an issue for what looks like a common problem but I have been cracking my teeth on this for days now.

Brew doctor throws the
```
Error: invalid byte sequence in UTF-8 with:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:338:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:331:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:295:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:241:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:240:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:239:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:239:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1258:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `doctor'
/usr/local/Library/brew.rb:124:in `<main>'
```

First, I checked the path looking for strange characters. This was the output:

/usr/local/bin:/usr/local/sbin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin

I found a broken symlink in my ruby.frameworks from Current to 1.8 and fixed that, but the problem persisted. I've gone through every issue and attempted many fixes, but none seem to work. I also fully reinstalled the essential.pkg from the Yosemite installer, hoping to replace ruby and any other development-related changes that could have been made in the last few years, but that didn't help either.

Here is the output of brew --config:

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: a9d599bf799bb898150d13b073541a2821409b49
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.10.4-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
MacPorts/Fink: /opt/local/bin/port
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /opt/local/bin/perl => /opt/local/bin/perl5.16
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_45

And my environment:

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/l4/lgvz2_w56ml52f35zhmlhgwh0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.5tDsmG0iTy/Render
TERM_PROGRAM_VERSION=343.7
TERM_SESSION_ID=0727783D-6A7C-490B-A334-80B231E8E916
USER=xxxx
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.5GlRyo6mnC/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin
PWD=/usr/local
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/xxxxxxx
LOGNAME=xxxxxx
DISPLAY=/private/tmp/com.apple.launchd.wFAxs8HiE6/org.macosforge.xquartz:0
_=/usr/bin/env
OLDPWD=/usr/local/Library/Homebrew

Thank you for your help!! It is much appreciated.

**Comment by DomT4** [comment]
Similar issue to #41632. Hmm.

Can you do `cd $(brew --prefix) && git status` and see if there's any uncommitted modifications and then a `brew readall`?

**Comment by marcusguttenplan** [comment]
Hey Dom, Thanks!

I tried checking the git, fetching, forcing a few times -- but nothing to commit. And no output from brew readall.

At one point I tried switching my bash profile to ASCII, but no solution. A few weeks ago I ran into a similar problem with multiple python versions stashed throughout my system, do you think this could be something similar with ruby?

**Comment by DomT4** [comment]
I don't know. We're fairly tight in ensuring we run off the back of the Ruby in `/System/Library/Frameworks/Ruby.framework` so multiple versions shouldn't cause issues in normal operation. Does the error only occur for you in `brew doctor` and no other commands? No issues with `brew update`, `brew upgrade`, `brew config` or any of that?

**Comment by marcusguttenplan** [comment]
All seem to be working fine, it's super strange! I'm looking through doctor.rb manually, hoping something will stand out.

**Comment by DomT4** [comment]
There's a lot that links into the `doctor` command. It's possible the error is being thrown by something merely linked into Doctor rather than from the Doctor code itself.

[This](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/doctor.rb#L236-L251) is the block the error message in the first post here are complaining about, but that was committed two years [ago](https://github.com/Homebrew/homebrew/commit/e8cec18e305b1894bed4b061ecf4dfa2f9a711b7) and seems unlikely to be throwing failures now.

The paths it'll be checking for stuff that can be pruned are `PRUNEABLE_DIRECTORIES = %w[bin etc include lib sbin share Frameworks LinkedKegs]`, but I'm not sure why those wouldn't be `UTF-8` friendly.

**Comment by DomT4** [comment]
CC @Homebrew/owners

**Comment by marcusguttenplan** [comment]
I noticed that my do command was not functioning earlier today, only as sudo. That would definitely cause that block to throw an error. Let me look into it.

**Comment by marcusguttenplan** [comment]
OK!

So I found a few issues. The first was two different self-referencing symlinks in the ruby framework. Second is what looks like a backdoor living in my usr/bin. Anytime it is input, with cd, ls, or rm, it opens a shell. How do I show you??

When I ls the /usr/bin, it shows up as "=ob<%C4?%A6pi?%FBV?ڦ?"?S%BB%BF%94%A0"

**Comment by marcusguttenplan** [comment]
Double OK!

There are multiple backdoors that use injection-y type stuff, once I clean house maybe that will solve it.

**Comment by marcusguttenplan** [comment]
I reported this to Apple as I am unsure how to sandbox it. Thanks for your help Dom!

**Comment by DomT4** [comment]
> "=ob<%C4?%A6pi?%FBV?ڦ?"?S%BB%BF%94%A0"

Yeah, I have absolutely no idea what could cause that sort of message. I'll leave this open in case any of the other maintainers have any new ideas on this failure, or if you discover further debugging information that could be useful.

**Comment by mistydemeo** [comment]
I've seen this occur as a result of filesystem corruption in the past. You may want to run a Disk Utility repair. What filesystem do you use?

**Comment by marcusguttenplan** [comment]
HFS+ in Yosemite. Disk utility is calling for a full recovery, sounds hopeful!

**Comment by DomT4** [comment]
Was this resolved by the recovery?

**Comment by marcusguttenplan** [comment]
It was not! Repairing the HD from recovery mode fixed the corrupted filename and from what I can tell all paths look clear, but still throwing the error. Works fine on a clean installation on another machine though, so I've messed something up.

**Comment by apjanke** [comment]
Repairing the HD with Disk Utility will get the filesystem metadata back in a valid state, but it doesn't get the contents of files back to their pre-corruption state if any data was changed. HFS+ has no data integrity features for file contents; only for directory metadata and internal filesystem structures. And the metadata recovery can be lossy: the new filesystem metadata state will be valid, but not necessarily exactly as it was before.

You might have residual corruption in file contents or an altered directory structure from the corruption, or from doing work while the corruption was in effect. I would do a full system reinstall.

**Comment by marcusguttenplan** [comment]
Thank you! A full reinstall solved everything. Now to start fixing adobe..
