### ISSUE TITLE
Mongodb --with-openssl failed to build on 10.10.4

### ISSUE THREAD

**Issue by Swammer** [Homebrew/homebrew#41971]
No gist logs because uninstalled to try to fix, but no luck.  

```
Swammer:~ $ brew install mongodb --with-openssl
==> Installing dependencies for mongodb: go, scons, openssl
==> Installing mongodb dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.4.2.yosemite.bottle.2.
######################################################################## 100.0%
==> Pouring go-1.4.2.yosemite.bottle.2.tar.gz
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin

==> Summary
🍺  /usr/local/Cellar/go/1.4.2: 4566 files, 155M
==> Installing mongodb dependency: scons
==> Downloading https://homebrew.bintray.com/bottles/scons-2.3.5.yosemite.bottle
######################################################################## 100.0%
==> Pouring scons-2.3.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/scons/2.3.5: 208 files, 2.4M
==> Installing mongodb dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.yosemite.b
######################################################################## 100.0%
==> Pouring openssl-1.0.2d_1.yosemite.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2d_1: 464 files, 18M
==> Installing mongodb
==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.0.4.tar.gz
######################################################################## 100.0%
==> Cloning https://github.com/mongodb/mongo-tools.git
Cloning into '/Library/Caches/Homebrew/mongodb--github.com-mongodb-mongo-tools--git'...
remote: Counting objects: 1175, done.
remote: Compressing objects: 100% (945/945), done.
remote: Total 1175 (delta 185), reused 812 (delta 137), pack-reused 0
Receiving objects: 100% (1175/1175), 1.83 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (185/185), done.
Checking connectivity... done.
Note: checking out 'efe71bf185cdcfe9632f1fc2e42ca4e895f93269'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

==> Checking out tag r3.0.4
==> ./build.sh ssl
==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.
                                                                    ^
1 error generated.
scons: *** [build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/mongo/db/storage/mmap_v1/dur_recovery_unit.o] Error 1
/usr/bin/clang++ -o build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/mongo/db/storage/mmap_v1/journal_latency_test_cmd.o -c -Wnon-virtual-dtor -Woverloaded-virtual -std=c++11 -fPIC -fno-strict-aliasing -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -Werror -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-unused-private-field -Wno-deprecated-declarations -Wno-tautological-constant-out-of-range-compare -Wno-unused-const-variable -Wno-missing-braces -Wno-null-conversion -mmacosx-version-min=10.10 -DBOOST_ALL_NO_LIB -D_SCONS -DMONGO_EXPOSE_MACROS -DPCRE_STATIC -DSUPPORT_UTF8 -DMONGO_OPTIMIZED_BUILD -DMONGO_BYTE_ORDER=1234 -D_FILE_OFFSET_BITS=64 -DMONGO_SSL -DMONGO_HAVE___THREAD -DMONGO_HAVE_CXX11_ATOMICS -DMONGO_HAVE_STD_IS_TRIVIALLY_COPYABLE -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_EXECINFO_BACKTRACE -I/usr/local/opt/openssl/include -Isrc/third_party/s2 -Isrc/third_party/pcre-8.37 -Isrc/third_party/boost -Ibuild/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl -Isrc src/mongo/db/storage/mmap_v1/journal_latency_test_cmd.cpp
scons: building terminated because of errors.

READ THIS: https://git.io/brew-troubleshooting
```

```
Swammer:~ $ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: e53f931c2c6f9759749eec6beaad88d3d685fd8c
Last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.10.4-x86_64
Xcode: 7.0 => /Applications/Xcode-beta.app/Contents/Developer
CLT: 7.0.0.0.1.1436025195
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: N/A
```

```
Swammer:~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libecomlodr.dylib
```

**Comment by dunn** [comment]
Can you try installing again to generate the build logs? Thanks!

**Comment by DomT4** [comment]
Ping?

**Comment by Swammer** [comment]
https://gist.github.com/bf317b5a75ffb1d8246d

I tried again and received the following different error this time:

```
==> Installing mongodb
==> Downloading https://fastdl.mongodb.org/src/mongodb-src-r3.0.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/mongodb-3.0.4.tar.gz
==> Cloning https://github.com/mongodb/mongo-tools.git
Updating /Library/Caches/Homebrew/mongodb--github.com-mongodb-mongo-tools--git
==> Checking out tag r3.0.4
==> ./build.sh ssl
==> /usr/local/opt/scons/bin/scons install --prefix=/usr/local/Cellar/mongodb/3.
                LOG(2) << "CUSTOM ROLLBACK " << demangleName(typeid(*_changes[i]));
                                                                    ^
1 error generated.
scons: *** [build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/mongo/db/storage/mmap_v1/dur_recovery_unit.o] Error 1
scons: building terminated because of errors.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Mongodb --with-openssl failed to build on 10.10.4 https://github.com/Homebrew/homebrew/issues/41971
```

Thanks!

**Comment by DomT4** [comment]
It's very possible the problem here is Xcode 7.0 changes. We applied a fix last week for El Capitan that may need stretching to cover all Xcode 7 users.

**Comment by Swammer** [comment]
Thanks, so would you recommend waiting until XCode 7 non-beta is released to install mongodb with openssl?

**Comment by DomT4** [comment]
It should work now, after a `brew update`, from some initial testing.

**Comment by anthonybrown** [comment]
@DomT4 I can confirm that it's still not working. Tried updating mongodb this morning and it failed.
```
/usr/bin/clang++ -o build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/use-system-boost/mongo/shell/linenoise.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -fno-strict-aliasing -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -O3 -Wno-unused-function -Wno-unused-private-field -Wno-deprecated-declarations -Wno-tautological-constant-out-of-range-compare -Wno-unused-const-variable -Wno-missing-braces -mmacosx-version-min=10.10 -D_SCONS -DMONGO_EXPOSE_MACROS -DPCRE_STATIC -DSUPPORT_UTF8 -DMONGO_OPTIMIZED_BUILD -DMONGO_BYTE_ORDER=1234 -D_FILE_OFFSET_BITS=64 -DMONGO_SSL -DMONGO_HAVE___THREAD -DMONGO_HAVE_GCC_ATOMIC_BUILTINS -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_THREAD_VERSION=2 -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_EXECINFO_BACKTRACE -DMONGO_HAVE_FIPS_MODE_SET -I/usr/local/opt/openssl/include -Isrc/third_party/s2 -Isrc/third_party/pcre-8.37 -Ibuild/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/use-system-boost -Isrc src/mongo/shell/linenoise.cpp
/usr/bin/clang++ -o build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/use-system-boost/mongo/shell/linenoise_utf8.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -fno-strict-aliasing -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -O3 -Wno-unused-function -Wno-unused-private-field -Wno-deprecated-declarations -Wno-tautological-constant-out-of-range-compare -Wno-unused-const-variable -Wno-missing-braces -mmacosx-version-min=10.10 -D_SCONS -DMONGO_EXPOSE_MACROS -DPCRE_STATIC -DSUPPORT_UTF8 -DMONGO_OPTIMIZED_BUILD -DMONGO_BYTE_ORDER=1234 -D_FILE_OFFSET_BITS=64 -DMONGO_SSL -DMONGO_HAVE___THREAD -DMONGO_HAVE_GCC_ATOMIC_BUILTINS -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_THREAD_VERSION=2 -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_EXECINFO_BACKTRACE -DMONGO_HAVE_FIPS_MODE_SET -I/usr/local/opt/openssl/include -Isrc/third_party/s2 -Isrc/third_party/pcre-8.37 -Ibuild/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/use-system-boost -Isrc src/mongo/shell/linenoise_utf8.cpp
2 warnings and 1 error generated.
scons: *** [build/darwin/cc__usr_bin_clang/cxx__usr_bin_clang++/osx-version-min_10.10/ssl/use-system-boost/mongo/shell/bench.o] Error 1
scons: building terminated because of errors.
```

**Comment by DomT4** [comment]
Can you post a full `brew-gist logs mongodb`, Thanks.

**Comment by anthonybrown** [comment]
Sure, thanks:https://gist.github.com/d119a960afbecfc247a1

**Comment by ajjublr** [comment]
Same issue, xcode new update (SSL) causes issue when trying to install mongodb with openssl. This is irrespective of the OSX version.

This may fix the issue as @DomT4 suggests - may need stretching to cover all Xcode 7 users

**Comment by anthonybrown** [comment]
`mongdb` working now
