### ISSUE TITLE
Unable to install wine on yosemite

### ISSUE THREAD

**Issue by huylv** [Homebrew/homebrew#42109]
It seems that brew can't download `libgphoto2` from sourceforge:

    $ brew install wine
    ==> Installing dependencies for wine: libgphoto2, libicns, makedepend,
    ==> Installing wine dependency: libgphoto2
    ==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5

    curl: (22) The requested URL returned error: 404 Not Found
    Error: Failed to download resource "libgphoto2"
    Download failed: https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.8/libgphoto2-2.5.8.tar.bz2

However, installing `libgphoto2` separately still works

    $ brew install libgphoto2
    ==> Downloading https://homebrew.bintray.com/bottles/libgphoto2-2.5.8.yosemite
    Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.8.yosemite.bottle.tar.gz
    ==> Pouring libgphoto2-2.5.8.yosemite.bottle.tar.gz
    🍺  /usr/local/Cellar/libgphoto2/2.5.8: 164 files, 4.6M

This happens to `libicns` as well. I have also tried all work-arounds mentioned in [issue 34257](https://github.com/Homebrew/homebrew/issues/34257) but none of them works for me.

Please advice. Thanks.

**Comment by mistydemeo** [comment]
Seems to still be MIA as part of the Great Sourceforge Downtime of 2015. Looking for mirrors.

**Comment by mistydemeo** [comment]
Should be fixed!

**Comment by huylv** [comment]
After issueing `brew update` it works now. But `libicns` is still not fixed. Could you please update it too. Thank you very much.

**Comment by dunn** [comment]
#42111.

**Comment by DevByStarlight** [comment]
Subject: homebrew wine and libgphoto2 upgrade conflict

# ~~

h4. Environment

Env: OSX Yosemite
Homebrew:
    $ brew --version 
    0.9.5

# ~~

h4. Summary

A homebrew install/upgrade conflict arises with libgphoto2.

    I have 'wine' installed.
    - 'wine' installs libgphoto2 as one of its dependencies.
    - It appears wine installs a particular version of libgphoto2.
      (different URL than default homebrew install of libgphoto2)

    If install either 'wine' or 'libgphoto2' they work individually - as long as the other hasn't already been installed.

    In other words, 'wine' installs okay unless 'libgphoto2' is already installed.
    And, libgphoto2 installs okay unless 'wine' has already been installed (since it installs a "different" 'libgphoto2').

    Consequently, an error arises when performing general brew updates/upgrades - 'brew upgrade'.

# ~~

h4. Wine/libgphoto2 Conflict

$ # Presently the 'libgphoto2' installed by 'wine'

$ brew uses --installed --recursive libgphoto2 
wine

    $ brew outdated
    libgphoto2 (2.5.7 < 2.5.8)

    $ brew upgrade outdated
    ==> Upgrading libgphoto2
    ==> Downloading https://fossies.org/linux/privat/libgphoto2-2.5.8.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.8.tar.bz2
    Error: SHA256 mismatch
    Expected: 031a262e342fae43f724afe66787947ce1fb483277dfe5a8cf1fbe92c58e27b6
    Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
    Archive: /Library/Caches/Homebrew/libgphoto2-2.5.8.tar.bz2
    To retry an incomplete download, remove the file above.



# ~~

h4. Install libgphoto2 THEN wine

A) Uninstall (partial) the libgphoto2 and wine packages
    NOTE:
        - Doing a non-recursive uninstall since I'm going to install again
          and don't wish to wait for all libgphoto2 dependenices.
        - The following illustrates the conflict issue sufficiently.

    $ brew uninstall wine libgphoto2
    Uninstalling /usr/local/Cellar/wine/1.6.2... (2057 files, 196M)
    Uninstalling /usr/local/Cellar/libgphoto2/2.5.8... (164 files, 7.6M)


B) Install libgphoto2 directly then try to install wine

    Note the different URLs (and tarballs) used for retrieving 'libgphoto2' libgphoto2


    $ brew install libgphoto2 
    ==> Downloading https://homebrew.bintray.com/bottles/libgphoto2-2.5.8.yosemite.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring libgphoto2-2.5.8.yosemite.bottle.tar.gz
        /usr/local/Cellar/libgphoto2/2.5.8: 164 files, 4.6M


    $ brew install wine       
    ==> Installing wine dependency: libgphoto2
    ==> Downloading https://fossies.org/linux/privat/libgphoto2-2.5.8.tar.bz2
    Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.8.tar.bz2
    Error: SHA256 mismatch
    Expected: 031a262e342fae43f724afe66787947ce1fb483277dfe5a8cf1fbe92c58e27b6
    Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
    Archive: /Library/Caches/Homebrew/libgphoto2-2.5.8.tar.bz2
    To retry an incomplete download, remove the file above.

    $ rm  /Library/Caches/Homebrew/libgphoto2-2.5.8.tar.bz2


    $ brew install wine
    ==> Installing wine dependency: libgphoto2
    ==> Downloading https://fossies.org/linux/privat/libgphoto2-2.5.8.tar.bz2
    ######################################################################## 100.0%
    ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.8
    ==> make install
    🍺  /usr/local/Cellar/libgphoto2/2.5.8: 164 files, 7.6M, built in 114 seconds
    ==> Installing wine
    ==> Downloading https://homebrew.bintray.com/bottles/wine-1.6.2.yosemite.bottle.tar.gz
    Already downloaded: /Library/Caches/Homebrew/wine-1.6.2.yosemite.bottle.tar.gz
    ==> Pouring wine-1.6.2.yosemite.bottle.tar.gz
    ==> Caveats
    You may want to get winetricks:
    ...

**Comment by mikemcquaid** [comment]
@DevByStarlight please create a new issue.
