### ISSUE TITLE
fmdiff failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42492]
https://gist.github.com/7b831d77b5783dc29ee1

**Comment by DomT4** [comment]
Is hardcoded to check for `Xcode.app` for testing. Fixed by GM Xcode 7.

**Comment by apjanke** [comment]
GM Xcode 7 only fixes it if you leave it at the default `/Applications/Xcode.app` path. I'm still getting breakage, because I version my Xcode installations.

This isn't 10.11-specific; the tag can be removed.

I'll report this upstream.

**Comment by apjanke** [comment]
There's no bug tracker listed for [upstream](http://bruno.defraine.net/fmdiff/); I sent the maintainer an email using the contact info on his page.

**Comment by DomT4** [comment]
To be honest, I'm not overly worried about that. The Xcode 7 GM is intended to be installed at `/Applications/Xcode.app`. If people want to install and move around different Xcode versions into that path, they should be able to handle the breakage that likely follows. If upstream want to handle it though, that's cool.
