### ISSUE TITLE
Error: Operation already in progress for protobuf

### ISSUE THREAD

**Issue by mzaiady** [Homebrew/homebrew#43520]
On Mac OSX:10.10.5

$rosdep install --from-paths src --ignore-src --rosdistro indigo -y

executing command [brew install gazebo]
==> Installing gazebo from osrf/homebrew-simulation
Error: Operation already in progress for protobuf
Another active Homebrew process is already using protobuf.
Please wait for it to finish or terminate it to continue.
ERROR: the following rosdeps failed to install
  homebrew: command [brew install gazebo] failed

**Comment by tdsmith** [comment]
Can you file this with the ROS project please?

**Comment by tdsmith** [comment]
Closing since I see https://github.com/ros-infrastructure/rosdep/issues/406 is open.

This can happen is a tap has a formula that duplicates the name of a formula in core. We can provide some assistance if there are questions.

**Comment by wjwwood** [comment]
@tdsmith I'd argue that if this can be caused by overlapping the formulae in taps, then the error message is wrong.

**Comment by wjwwood** [comment]
@mzaiady What happens if you just run `brew install gazebo`?

**Comment by wjwwood** [comment]
I just ran `brew install gazebo` successfully, then I uninstall it, did `brew update` and then ran it again and I get the same failure as @mzaiady:

```
% brew install gazebo
==> Installing gazebo from osrf/homebrew-simulation
Error: Operation already in progress for protobuf
Another active Homebrew process is already using protobuf.
Please wait for it to finish or terminate it to continue.
```

I'd say this is a new bug in Homebrew, or if this is expected the error message is incorrect.

**Comment by tdsmith** [comment]
I agree it's not a good error message. Whoever maintains the gazebo formula may need to use a fully-qualified formula name in their depends_on declaration; IIRC the entire dependency tree of a formula may refer to at most one formula with a given short name.

Where can we find this formula?

**Comment by wjwwood** [comment]
> Where can we find this formula?

https://github.com/osrf/homebrew-simulation/blob/master/gazebo.rb

**Comment by wjwwood** [comment]
@scpeters fyi

**Comment by tdsmith** [comment]
Okay, I see. This is ultimately a long-standing Homebrew bug but the workaround is to avoid tap formulas with the same name as core formulas. homebrew-julia is an example of an implementation. https://github.com/staticfloat/homebrew-julia/

**Comment by tdsmith** [comment]
Background reading includes #14089, #17730, Homebrew/homebrew-science#767.

**Comment by tdsmith** [comment]
Alternatively, if the protobuf fix has been committed upstream by now, we can pull the patch into Homebrew/homebrew.

**Comment by scpeters** [comment]
I maintain the gazebo formulae and the duplicate protobuf formula is no longer necessary; our error was unrelated to the patch. I just haven't gotten around to deleting it and modifying the gazebo formula accordingly. I'll do so as soon as this discussion is resolved.

I concur that the error message is not very helpful. If it is non-trivial to detect this during install, perhaps an audit rule could be created? The gazebo formula currently passes `brew audit --strict`.

**Comment by brothaman** [comment]
Hello I'm currently trying to install the gazebo simulation and im getting the same error
```
==> Installing gazebo from osrf/homebrew-simulation
Error: Operation already in progress for protobuf
Another active Homebrew process is already using protobuf.
Please wait for it to finish or terminate it to continue.
```
I've tried ``` brew audit --strict ``` &  ```brew install gazebo --only-dependencies``` then ``` brew install gazebo ``` and still the same error. Is there a recommended work around or maybe some other formula where this has been been resolved?

**Comment by scpeters** [comment]
I'm fixing the gazebo formula in https://github.com/osrf/homebrew-simulation/pull/46
