### ISSUE TITLE
`pip3 install numpy` fails on Python 3.5

### ISSUE THREAD

**Issue by prophile** [Homebrew/homebrew#43916]
Appears to be due to `Python.h` being absent.

```
[snip]
    File "numpy/core/setup.py", line 293, in check_types
      "Cannot compile 'Python.h'. Perhaps you need to "\
  SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
  
  ----------------------------------------
  Failed building wheel for numpy
Failed to build numpy
ERROR: Failed to build one or more wheels
```

Mac OS X 10.10.

**Comment by xu-cheng** [comment]
Homebrew offers numpy formula, you can try `brew install homebrew/python/numpy --with-python3`.

**Comment by tdsmith** [comment]
This is a numpy.distutils bug: https://github.com/numpy/numpy/pull/5866

It's fixed in the development tree. The homebrew-python formula applies a patch.

You wouldn't have noticed on 3.4 because the numpy and scipy projects publish wheels, which are used in preference to building from source. Those will probably be published soon.

You can install the current numpy development version like `pip3 install git+https://github.com/numpy/numpy.git`.

**Comment by azag0** [comment]
Installing Numpy with Homebrew succeeds, but the imported module is empty in brewed Python 3.5 (only `__` attributes). The same Numpy installation works correctly in Apple Python. I used the `--with-python3` option.

**Comment by prophile** [comment]
I'm sure the Homebrew `numpy` works but this appears to be a wider problem with building wheels from any module with a C extension.

**Comment by xanderdunn** [comment]
@tdsmith Thanks!

**Comment by tdsmith** [comment]
This is resolved by the release of numpy 1.9.3: https://github.com/numpy/numpy/blob/v1.9.3/doc/release/1.9.3-notes.rst

**Comment by ClarkKentt** [comment]
I think this is still not working.
Tried both 
>pip3 install numpy

and

>pip3 install git+https://github.com/numpy/numpy.git

and nothing happens:
https://gist.github.com/ClarkKentt/3b40b19ce8205fd152b6
Python 3.5

**Comment by SachitNayak** [comment]
@ClarkKentt that's true 
both don't work
I tried cloning the dev version too. 
pip3 install git+https://github.com/numpy/numpy.git
sadly doesn't work
both methods give the same error

**Comment by mikemcquaid** [comment]
Please open a new issue.

**Comment by mikemcquaid** [comment]
And follow the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!
