### ISSUE TITLE
srclib fails to download/build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44004]
srclib is failing to build for me on 10.11. It is failing during the resource download stage, so no logs are generated for me to post.

It downloads the main tarball and a bunch of go resources okay. And then one of them fails.

```
==> Cloning https://github.com/sourcegraph/go-flags
Updating /Library/Caches/Homebrew/srclib--sourcegraph.com-sourcegraph-go-flags--git
git config remote.origin.url https://github.com/sourcegraph/go-flags
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
git checkout -f f819544216a8b66157184f0976948f92a8144fe7 --
fatal: reference is not a tree: f819544216a8b66157184f0976948f92a8144fe7
Error: Failed to download resource "srclib--sourcegraph.com-sourcegraph-go-flags"
Failure while executing: git checkout -f f819544216a8b66157184f0976948f92a8144fe7 --
```

That commit `f819544216a8b66157184f0976948f92a8144fe7` it is referencing is not in the main repo history; it's in a pending Pull Request, sourcegraph/go-flags#1. When I try to clone and check it out manually, I need to do an extra fetch to get the PR content before that checkout will work.

Seems like this was working before, since there's only been one version of the formula (from #37651), and it passed the brew test bot tests. Maybe sourcegraph/go-flags rewrote their repo history, changing the commit identifiers?

Kinda seems like it. The referenced commit, which shows up in that PR, is about "adding initfuncs", and was authored and commited in Dec 2014.

<img width="893" alt="screen shot 2015-09-16 at 2 04 35 am" src="https://cloud.githubusercontent.com/assets/2618447/9898399/719ffba2-5c17-11e5-93ea-a1f18bed3f01.png">

But recently there was a commit with a similar looking "adding initfuncs" authored on Dec 2014, but committed in April 2015 and with a different commit identifier, after the Homebrew srclib formula was added in March 2015. 

<img width="877" alt="screen shot 2015-09-16 at 2 04 47 am" src="https://cloud.githubusercontent.com/assets/2618447/9898419/b0517164-5c17-11e5-9eb3-1d059a1cbbf6.png">

Looks like maybe a giant rebase was done? And that open PR is old enough that it preserved the old version of that commit? Or do I just not understand how the commit IDs work with resource downloads here?

Frickin' GitHub workflows.

**Comment by tzenderman** [comment]
Having the same exact issue +1

**Comment by adin234** [comment]
any solutions?

**Comment by apjanke** [comment]
Hi @samertm. You were the original author of the `srclib` formula. Do you remember how you got the SHAs for the go resources, especially `sourcegraph.com/sourcegraph/go-flags`, and whether something might have invalidated that commit?

We could probably just switch to using whichever reversion of that resource was (now retroactively) the latest as of the time of the srclib 0.0.42 release.

And there have been several newer releases of srclib since then, up to [0.1.1](https://github.com/sourcegraph/srclib/releases/tag/v0.1.1), if someone wants to just do a version bump. I'm not that familiar with `go_resource` so I'm not sure I can do that myself easily.

**Comment by apjanke** [comment]
Removing 10.11 label. It's not 10.11-specific; it's just that 10.11 didn't have a bottle built for it, and this is a build-time failure, so that's where it showed up.

**Comment by apjanke** [comment]
Here's a PR that does so: #47870.

`brew test srclib` is failing for this. I don't think this is a regression, though, because `brew test srclib` fails with the same issue with existing formula on 10.9 for me.

```
$ brew test srclib
Testing srclib
==> Using the sandbox
==> Downloading https://github.com/sourcegraph/srclib-sample/archive/0.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/srclib--srclib-sample-0.1.tar.gz
==> /usr/local/Cellar/srclib/0.0.42_1/bin/src toolchain add --force sourcegraph.com/s
Last 15 lines from /Users/janke/Library/Logs/Homebrew/srclib/01.src:
2016-01-08 20:35:27 -0500

/usr/local/Cellar/srclib/0.0.42_1/bin/src
toolchain
add
--force
sourcegraph.com/sourcegraph/srclib-sample

2016/01/08 20:35:27 Failed to detect git/hg repository root dir for "."; continuing.
mkdir /Users/janke/.srclib: operation not permitted
Error: srclib: failed
Failed executing: /usr/local/Cellar/srclib/0.0.42_1/bin/src toolchain add --force sourcegraph.com/sourcegraph/srclib-sample
/usr/local/Library/Homebrew/formula.rb:1472:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1409:in `open'
/usr/local/Library/Homebrew/formula.rb:1409:in `system'
/usr/local/Library/Formula/srclib.rb:201:in `block (2 levels) in <class:Srclib>'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Formula/srclib.rb:199:in `block in <class:Srclib>'
/usr/local/Library/Homebrew/formula.rb:1318:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1314:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

Anybody know how to fix this? Is it appropriate to just `git init .` the test directory?

**Comment by apjanke** [comment]
The resource revision change worked (#47870) and I've merged it, without updating to the newer srclib release. `brew install srclib` should work again on all OS X versions now; let us know if you still have failures.

Anybody want to take a stab at updating to the current srclib version, feel free.

**Comment by adin234** [comment]
@apjanke it still doesnt work though. 

![screen shot 2016-01-11 at 9 18 54 am](https://cloud.githubusercontent.com/assets/3828145/12225368/6461f2e0-b844-11e5-9ec9-b7e81ebe610d.png)

**Comment by apjanke** [comment]
@adin234: Make sure you've done a `brew update` and picked up the latest revision of `srclib.rb`, and that you don't have any local changes that are preventing it from updating. That `f819544216...` revision in your screen shot is from the old pre-#47870 version of the formula.
