### ISSUE TITLE
mitmproxy failed to build on 10.11

### ISSUE THREAD

**Issue by agatti** [Homebrew/homebrew#44556]
Installing mitmproxy with ```brew install mitmproxy --with-protobuf --with-cssutils --with-pyamf``` fails, as it is using the system Python installation (which is missing ffi.h) even if homebrew Python is also installed.

Gist logs at https://gist.github.com/anonymous/e9d07ea7c55f33c7f2ed

Thank you!

**Comment by DomT4** [comment]
Doesn't reproduce with the Command Line Tools installed for me. I presume `/usr/include/ffi/ffi.h` doesn't exist on your machine?

**Comment by agatti** [comment]
I don't happen to have ```/usr/include``` either.  ```ffi.h``` is located in ```/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ffi```.  No Command Line Tools installed as far as I know, but brew didn't complain about that (didn't it use to ask for that package to be installed?).

**Comment by DomT4** [comment]
> No Command Line Tools installed as far as I know, but brew didn't complain about that (didn't it use to ask for that package to be installed?).

We only require Xcode or the CLT for 99% of formulae. This isn't intended to be part of the 1% that requires both.

`superenv` is passing ` -I/usr/include/ffi -I/usr/include/libffi`, so perhaps we can work around this by adding a `CFLAG` to the SDK path when the CLT isn't installed.

This seems to happen a lot on non-CLT systems with `cffi`.

**Comment by DomT4** [comment]
Should be fixed once #45078 is merged.

**Comment by agatti** [comment]
Has #45078 been merged?  I just tried to install mitmproxy on 10.11.2 and the problem I reported is still occurring with no CLT installed.  I got newer logs at https://gist.github.com/fe2e7701d63d4300e7ea just in case.
