### ISSUE TITLE
Fail to download the newest "ImageMagick"

### ISSUE THREAD

**Issue by irini** [Homebrew/homebrew#45015]
I've tried to install ImageMagick in my VPS, and here's what I got:

```
==> Downloading http://www.imagemagick.org/download/releases/ImageMagick-6.9.2-3.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-3.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "imagemagick"
Download failed: http://ftp.nluug.nl/ImageMagick/ImageMagick-6.9.2-3.tar.xz
```

What can I do?

**Comment by DomT4** [comment]
`brew update`. We merged in `6.9.2-4` four days ago.

**Comment by irini** [comment]
I've already update, and when I used <code>brew update</code> again I got:
```
Already up-to-date.
```

But still cannot download ImageMagick and got the same message...

**Comment by DomT4** [comment]
Can you `brew config` and perhaps `cd $(brew --prefix) && git status`? Thanks.

**Comment by irini** [comment]
I just noticed I've used **Linuxbrew**, maybe this is the problem. Can I use **Homebrew** in my VPS (CentOS)?

**Comment by DomT4** [comment]
You can't use Homebrew itself on Linux platforms as Linuxbrew adds quite a few workarounds to make it play nicely with a lot of things that don't quite work the same way on Linux as they do Darwin, sadly.

It's likely Linuxbrew hasn't been synced up with Homebrew yet, hence the issue. Linuxbrew tends to get weekly syncs which brings it back in line with Homebrew. The latest is pending review and merge as noted in https://github.com/Homebrew/linuxbrew/issues/600#issuecomment-148552661 and should be done soon. I'd keep an eye on that topic for a reply there and then `brew update` and `brew install imagemagick` at that point :)
