### ISSUE TITLE
brew install ejabberd --HEAD failed 

### ISSUE THREAD

**Issue by vitalyster** [Homebrew/homebrew#46460]
https://gist.github.com/anonymous/f4657de1a979bed82cdd

**Comment by dunn** [comment]
Should work now. Thanks for the report!

**Comment by vitalyster** [comment]
Still does not work:
https://gist.github.com/anonymous/7eb4ec5352c1cd641949

**Comment by dunn** [comment]
Not sure what's happening here.  Can you try removing the cached downloads and trying again?

**Comment by vitalyster** [comment]
```
rm -rf `brew --cache`
```
nothing changes

**Comment by dunn** [comment]
Ha, I cleared _my_ cache and now I'm seeing the same thing.

**Comment by dunn** [comment]
OK I think I got it right with d829586861d28293b046eff2bc9a4aab6991a409.

**Comment by vitalyster** [comment]
Works now, thanks
